Replaced registered trademark symbol with ASCII version
intel/libvpl pull request #118
Opened 2024-01-11 01:17 UTC by mmhat

## Issue

The "®" was not conforming to [RFC-822](https://www.w3.org/Protocols/rfc822/#:~:text=3.2.%20HEADER%20FIELD%20DEFINITIONS) and broke downstream build tools; See https://github.com/haskell/cabal/issues/9608 for an example.

Fixes #117 

## Solution

Just replaced the symbol with `(R)`. This appears to be the go-to solution is also used by other packages, e.g. <https://github.com/intel/gmmlib/blob/f5943626a108245a31290811f41338e7151ac22d/Source/GmmLib/igdgmm.pc.in>.

## How Tested

Tested it locally by running a [Cabal](https://github.com/haskell/cabal) build which was failing before.

2024-01-11 17:34 UTC, mav-intel requested changes
Thanks for the PR. A few changes requested:
Per [CONTRIBUTING.md](https://github.com/intel/libvpl/blob/master/CONTRIBUTING.md)

- Please sign-off on the PR
- Please change the commit message to be imperative.  I would recommend: `Use only ASCII text in pkg-config file`

Also, please Update the changelog, adding the following under unreleased: 
```
### Fixed
- "®" symbol in pkg-config file breaking downstream build tools
```

2024-01-23 02:25 UTC, bradrn commented
This issue is affecting many people, in https://github.com/haskell/cabal/issues/9608 and presumably elsewhere too. It would be good to get this fix merged please!

2024-01-23 23:37 UTC, mav-intel commented
Since original submitter has not had a chance to make requested changes, pushed my own version of this PR as #121 and closing this one

2024-01-23 23:37 UTC, closed without merging

2024-01-24 00:16 UTC, bradrn commented
Thanks!